import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import { Container } from "react-bootstrap";
import TopNav from "./_components/TopNav/TopNav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-black text-light`}>
        <Container>
          <TopNav />
          {children}
        </Container>
      </body>
    </html>
  );
}
